"""empty message

Revision ID: 7ba1c859e52f
Revises: 05f0642f1600
Create Date: 2020-12-29 15:32:09.304268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba1c859e52f'
down_revision = '05f0642f1600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_of_birth', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'city_of_birth')
    # ### end Alembic commands ###
